version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: my_database
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend-resenas
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
    volumes:
      - ./backend-resenas:/app
      - ./backend-resenas/uploads:/app/uploads
    depends_on:
      - db

  frontend:
    build: ./aplicacion-resenas
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_IMG_URL: ${REACT_APP_IMG_URL}

    volumes:
      - ./aplicacion-resenas:/app
    depends_on:
      - backend

volumes:
  db_data:
